[package]
name = "binary-merkle-tree"
version = "13.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
repository.workspace = true
description = "A no-std/Substrate compatible library to construct binary merkle tree."
homepage = "https://substrate.io"

[lints]
workspace = true

[dependencies]
array-bytes = { optional = true, workspace = true, default-features = true }
log = { optional = true, workspace = true }
trie-db = { package = "subtrie", version = "0.0.1", default-features = false }

[dev-dependencies]
array-bytes = { workspace = true, default-features = true }
env_logger = { workspace = true }
sp-core = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }

[features]
debug = ["array-bytes", "log"]
default = ["debug", "std"]
std = ["log/std", "sp-core/std", "sp-runtime/std", "trie-db/std"]
