[package]
name = "sp-trie"
version = "29.0.0"
authors.workspace = true
description = "Patricia trie stuff using a parity-scale-codec node format"
repository.workspace = true
license = "Apache-2.0"
edition.workspace = true
homepage = "https://substrate.io"
documentation = "https://docs.rs/sp-trie"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bench]]
name = "bench"
harness = false

[dependencies]
ahash = { optional = true, workspace = true }
codec = { workspace = true }
lazy_static = { optional = true, workspace = true }
nohash-hasher = { optional = true, workspace = true }
parking_lot = { optional = true, workspace = true, default-features = true }
rand = { optional = true, workspace = true, default-features = true }
scale-info = { features = ["derive"], workspace = true }
thiserror = { optional = true, workspace = true }
tracing = { optional = true, workspace = true, default-features = true }
trie-db = { package = "subtrie", version = "0.0.1", default-features = false }
sp-core = { workspace = true }
sp-externalities = { workspace = true }
schnellru = { optional = true, workspace = true }

[dev-dependencies]
array-bytes = { workspace = true, default-features = true }
criterion = { workspace = true, default-features = true }
trie-db = { package = "subtrie", version = "0.0.1", features = ["bench"] }
sp-runtime = { workspace = true, default-features = true }

[features]
default = ["std"]
std = [
	"ahash",
	"codec/std",
	"lazy_static",
	"nohash-hasher",
	"parking_lot",
	"rand",
	"scale-info/std",
	"schnellru",
	"sp-core/std",
	"sp-externalities/std",
	"sp-runtime/std",
	"thiserror",
	"tracing",
	"trie-db/std",
]
